### ISSUE TITLE
TypeError: _handle_redirect_headers() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by dpursehouse** [jwaschkau/django-unpoly#13]
* django-unpoly version: 0.1.2
* Python version: Python 3.9.7
* Operating System: OSX

### Description

On a request that results in a redirect, django-unpoly crashes with:

```
2021-09-25 19:58:30,512:    ERROR -- Internal Server Error: /redacted/18/
Traceback (most recent call last):
  File "/Users/dpursehouse/myproject/.tox/py38/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/dpursehouse/myproject/.tox/py38/lib/python3.8/site-packages/django_unpoly/middleware.py", line 72, in __call__
    response = self._handle_redirect_headers(request, response)
TypeError: _handle_redirect_headers() takes 2 positional arguments but 3 were given
```

### What I Did

Looking at the code, the method is defined as:

```
def _handle_redirect_headers(self, response: HttpResponseBase):
```

but is called with:

```
response = self._handle_redirect_headers(request, response)
```

**Comment by dpursehouse** [comment]
Seems to have been introduced by 5341997acd22844be4372adfad12ef2a4ad0d382

**Comment by jwaschkau** [comment]
@dpursehouse Thanks for the bug report. I will upload a fixed version to PyPi.

**Comment by dpursehouse** [comment]
Thanks @jwaschkau , it's working now!
